# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 5148:5148
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "server=db;database=Blog;user=sa;password=P@ssw0rd;TrustServerCertificate=true"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    ports:
      - "5434:1433"